# build environment
FROM node:13.12.0-alpine as build
WORKDIR /frontend

ENV NODE_ENV=production
ENV REACT_APP_API_URL=http://g22-iic2173.tk/api
ENV REACT_APP_SOCKET_URL=http://g22-iic2173.tk

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

# stage
FROM nginx:latest
COPY --from=build /frontend/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
