version: 0.0
os: linux

files:
  - source: scripts
    destination: /ci-cd-node/
permissions:
  - object: scripts
    pattern: "**"
    owner: ec2-user
hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 600
      runas: ec2-user
  AfterInstall:
    - location: install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 600
      runas: ec2-user
