version: "3"
services:
  chat-frontend:
    build:
      context: ./frontend
    container_name: develop_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_SOCKET_URL=http://localhost:8080
      - SKIP_PREFLIGHT_CHECK=true
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    stdin_open: true

  chat-backend:
    build:
      context: ./backend
    container_name: develop_backend
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=postgresql
      - DB_NAME=chat_development
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - FRONTEND_URL=http://localhost:3000
    env_file:
      - ./backend/.env
    depends_on:
      - postgresql

  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_DB=chat_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
